### ISSUE TITLE
Older version support

### ISSUE THREAD

**Issue by Dexi89** [WearBlackAllDay/SeedCandy#1]
Will support for 1.12 and below be added?

**Comment by WearBlackAllDay** [comment]
I have the code for most of SeedCandy´s features in lower versions ready, the main issue is currently single-dungeon reversal in lower versions. However if i am ever supporting additional versions i am going to support every feature the tool has to offer, because partial support is toxic imo. 
For 1.12 i am not neccessarily saying it wont happen, but since i am not personally interested in 1.12 all that much, it prolly wont in the near future.
